# -*- coding: utf-8 -*-
"""Task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7C3l-wVq38UUprEyDhTOoYRIQqROSwq
"""

import os
import cv2
import numpy as np

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

dataset_path = r"C:\Users\Vignesh\Downloads\Food11"

X = []
Y = []

label_dict = {}
label = 0

for food in os.listdir(dataset_path):

    food_path = os.path.join(dataset_path, food)

    if os.path.isdir(food_path):

        label_dict[label] = food

        for image_name in os.listdir(food_path):

            image_path = os.path.join(food_path, image_name)

            try:
                img = cv2.imread(image_path)

                img = cv2.resize(img, (64, 64))

                img = img.flatten()

                X.append(img)

                Y.append(label)

            except:
                pass

        label += 1

X = np.array(X)
Y = np.array(Y)

print("Total Images:", len(X))

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

model = SVC(kernel='linear')

model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

accuracy = accuracy_score(Y_test, Y_pred)

print("Accuracy:", accuracy * 100, "%")

calories = {
    "Bread": 265,
    "Dairy": 150,
    "Dessert": 300,
    "Egg": 155,
    "Fried_Food": 320,
    "Meat": 250,
    "Noodles": 138,
    "Rice": 130,
    "Seafood": 206,
    "Soup": 75,
    "Vegetables": 65
}

test_image = r"C:\Users\Vignesh\Downloads\food.jpg"

img = cv2.imread(test_image)

img = cv2.resize(img, (64, 64))

img = img.flatten()

prediction = model.predict([img])

food_name = label_dict[prediction[0]]

print("\nPredicted Food:", food_name)

if food_name in calories:
    print("Estimated Calories:", calories[food_name], "kcal per 100g")
else:
    print("Calories Not Available")